<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<?php echo $GLOBALS['description'] ?>">
    <meta name="keywords" content="<?php echo $GLOBALS['keywords'] ?>">
    <meta name="author" content="<?php echo $GLOBALS['author'] ?>">

    <title>
        <?php echo $GLOBALS['title'] ?>
    </title>

    <!-- Bootstrap core CSS -->
    <link href="../static/bootstrap3.3.2/css/bootstrap.css" rel="stylesheet">
    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <link rel="icon" href="/favicon.ico">
</head>
<body>
<!-- Docs master nav -->
<header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">
    <div class="container">
    </div>
</header>

<div class="container bs-docs-container">
    <form action="qqDetailTool.php?action=importData" method="post" onsubmit="return importcfm()">
        <div class="form-group">
            <label for="exampleInputEmail1">导入时间,格式：<?php echo date("Y-m-d H:i:s",time()); ?></label>
            <input type="text" name="CreateTime" class="form-control" id="CreateTime" value="<?php echo date("Y-m-d H:i:s",time()); ?>">
        </div>
        <div class="form-group">
            <div>文件列表</div>
            <?php
            foreach ($aFilesNames as $key => $value) {
                ?>
                <label class="radio-inline">
                    <input type="radio" name="sFileName" id="sFileName<?php echo $key; ?>"
                           value="<?php echo $value; ?>"> <?php echo $value; ?>
                </label>
            <?php
            } ?>
        </div>
        <div class="form-group">
            <div>导入种类(只有普通导入支持excel导入，且excel只适合小额导入，慎用)</div>
                <label class="radio-inline">
                    <input type="radio" name="iImportType" id="iImportType1"
                           value="0">普通导入
                </label>
            <label class="radio-inline">
                <input type="radio" name="iImportType" id="iImportType2"
                       value="1">导入验证类型
            </label>
            <label class="radio-inline">
                <input type="radio" name="iImportType" id="iImportType3"
                       value="2">导入生日
            </label>
        </div>
        <div class="form-group">
            <button type="submit" class="btn btn-primary">导入文件</button>
        </div>
    </form>
</div>

<!-- Footer
================================================== -->
<footer class="bs-docs-footer" role="contentinfo">
    <div class="container">
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="../static/jquery/jquery-2.1.1.js"></script>


<script src="../static/bootstrap3.3.2/js/bootstrap.js"></script>
<script language="javascript">
    function importcfm() {
        if (confirm('确定继续？')) {
            return true;
        } else {
            return false;
        }
    }
</script>

</body>
</html>
