<?php include($GLOBALS['VIEWPATH'].'header.phtml'); ?>
<style>
    .padding-left-5{
        padding-left: 5px;
    }
    .icon-class {
        font-size: 14px;
        color: #cccccc;
    }
    .icon-class-add {
        font-size: 18px;
        color:#666666;
    }
</style>
<div class="container bs-docs-container">
    <header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">
        <h1 class="text-center">任务列表</h1><a href="?action=initBatchPage" title="新增任务"><button type="button" class="icon-class-add btn btn-default">新增任务</button></a>
        <a href="?action=batchSeccList" title="任务执行成功列表"><button type="button" class="icon-class-add btn btn-default">任务执行成功列表</button></a>
    </header>
    <div class="pbody clearfix">
        <table class="table table-bordered table-hover">
            <thead>
            <tr>
                <th class="text-center">创建时间</th>
                <th class="text-center">群发年龄段</th>
                <th class="text-center">发送日期</th>
                <th class="text-center">发送时间</th>
                <th class="text-center">发送文章</th>
                <th class="text-center">操作</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($aData as $v) { ?>
                <tr id="tr_<?php echo $v['id'] ?>">
                    <td class="text-center"><?php echo date('Y-m-d H:i:s',$v['created_at']) ?></td>
                    <td class="text-center"><?php echo $v['send_age']; ?>个月</td>
                    <td class="text-center"><?php echo $v['send_date']; ?>号</td>
                    <td class="text-center"><?php echo $aTime[$v['send_time']]; ?></td>
                    <td class="text-center">
                        <?php
                        if(isset($aMediaList['list'][$v['media_id']])) {
                            $aMedia = $aMediaList['list'][$v['media_id']];
                            foreach ($aMedia as $key => $value) {
                                ?>
                                <a target="_blank" href="<?php echo $value['url'];?>"><?php echo $value['title'];?></a><br>
                        <?php
                            }
                        }
                        ?>
                    </td>
                    <td class="text-center">
                        <a class="icon-class" href="?action=initBatchPage&id=<?php echo $v['id'] ?>" title="编辑"><span class="glyphicon glyphicon-pencil" aria-hidden="true"></span></a>
                        <a class="icon-class news_delete" href="?action=deleteBatch&id=<?php echo $v['id'] ?>" role="button"
                           data-toggle="modal" title="删除"><span class="glyphicon glyphicon-trash" aria-hidden="true"></span></a>
                    </td>
                </tr>
            <?php } ?>
            </tbody>
        </table>

    </div>
</div>
<script>
    $('.news_delete').click(function () {
        if (confirm("您确认要删除该任务吗？")) {
            $.get(this.href, function (ret) {
                alert(ret.data);
                if (ret.status) {
                    location.reload();
                }
            }, 'json');
        }
        return false;
    });
</script>

<?php include($GLOBALS['VIEWPATH'].'footer.phtml'); ?>
