<?php include($GLOBALS['VIEWPATH'] . 'header.phtml'); ?>

<!-- Docs master nav -->
<header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">
    <h1 class="text-center"><?php echo isset($aData) ? '编辑' : '创建' ?>定时群发分组任务</h1>
</header>


<div class="container bs-docs-container">
    <form action="?action=initBatch" method="post">
        <input type="hidden" value="<?php echo isset($aData) ? $aData['id'] : '' ?>" name="id">
        <div class="form-group">
            <div class="margin_aa"><label>
                    选择年龄段
                </label></div>
            <div class="form-inline">
                <div class="form-group">
                    <select name="batchAge" class="form-control" style="width: 150px">
                        <option value="10000">请选择年龄段</option>
                        <?php
                        if (!empty($aAgeList)) {
                            foreach ($aAgeList as $key => $value) {
                                ?>
                                <option <?php echo (isset($aData) && $aData['send_age'] == $value) ? 'selected' : '' ?> value="<?php echo $value ?>"><?php echo $value ?>个月</option>
                            <?php
                            }
                        }
                        ?>
                    </select>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="margin_aa"><label>
                    选择图文模版
                </label></div>
            <div class="form-inline">
                <div class="form-group">
                    <?php
                    if (!empty($aMediaList['item'])) {
                        foreach ($aMediaList['item'] as $key => $value) {
                            ?>
                            <div class="radio">
                                <label>
                                    <input <?php echo (isset($aData) && $aData['media_id'] == $value['media_id']) ? 'checked' : '' ?> type="radio" name="media_id" id="media_id"
                                           value="<?php echo $value['media_id']; ?>">
                                </label>
                            </div>
                            <div class="media-div">
                                <?php
                                foreach ($value['content']['news_item'] as $k => $val) {
                                    ?>
                                    <div class="appmsg_item">
                                        <h4><a target="_blank"
                                               href="<?php echo $val['url']; ?>"><?php echo $val['title']; ?></a></h4>
                                    </div>
                                <?php
                                }
                                ?>
                            </div>
                        <?php

                        }
                    }
                    ?>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="margin_aa"><label>
                    选择发送日期
                </label></div>
            <select name="batchDate" class="form-control" style="width: 150px">
                <option value="">请选择发送日期</option>
                <?php
                if (!empty($aDateList)) {
                    foreach ($aDateList as $key => $value) {
                        ?>
                        <option <?php echo (isset($aData) && $aData['send_date'] == $value) ? 'selected' : '' ?> value="<?php echo $value ?>"><?php echo $value ?>号</option>
                    <?php
                    }
                }
                ?>
            </select>
        </div>
        <div class="form-group">
            <div class="margin_aa"><label>
                    选择群发时间
                </label></div>
            <div class="form-inline">
                <div class="form-group">
                    <?php
                    if (!empty($batchTime)) {
                        foreach ($batchTime as $key => $value) {
                            ?>
                            <label>
                                <input <?php echo (isset($aData) && $aData['send_time'] == $key) ? 'checked' : '' ?> type="radio" name="batchTime" id="batchTime"
                                       value="<?php echo $key; ?>"> <?php echo $value; ?>
                            </label>
                        <?php
                        }
                    }
                    ?>
                </div>
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn-lg">提交</button>
</div>
</form>
<?php include($GLOBALS['VIEWPATH'] . 'footer.phtml'); ?>

