<style xmlns="http://www.w3.org/1999/html">
    .margin_aa {
        margin-bottom: 10px;
    }

    .form-select-css {
        width: 100px;
    }
    .media-div {
        width: 295px;
        border:1px solid #204d74;
    }
    .media-image {
        float: right;
    }
    .clear {
        clear: both;
    }
</style>
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<?php echo $GLOBALS['description'] ?>">
    <meta name="keywords" content="<?php echo $GLOBALS['keywords'] ?>">
    <meta name="author" content="<?php echo $GLOBALS['author'] ?>">

    <title>
        <?php echo $GLOBALS['title'] ?>
    </title>

    <!-- Bootstrap core CSS -->
    <link href="../../static/bootstrap3.3.2/css/bootstrap.css" rel="stylesheet">
    <link href="../../static/plug-in/ladytime/css/bootstrap-datetimepicker.min.css" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <link rel="icon" href="/favicon.ico">
</head>
<body>
<!-- Docs master nav -->
<header class="navbar navbar-static-top bs-docs-nav" id="top" role="banner">
    <h1 class="text-center">创建定时群发分组任务</h1>
</header>


<div class="container bs-docs-container">
    <form action="?action=initBatch" method="post">
    <div class="form-group">
        <div class="margin_aa"><label>
                选择分组
            </label></div>
        <div class="form-inline">
            <div class="form-group">
                <select name="group_id" class="form-control" style="width: 150px">
                    <option value="10000">请选择分组</option>
                    <?php
                    if (!empty($aGroupList['groups'])) {
                        foreach ($aGroupList['groups'] as $key => $value) {
                            ?>
                            <option value="<?php echo $value['id'] ?>"><?php echo $value['name'] ?></option>
                        <?php
                        }
                    }
                    ?>
                </select>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="margin_aa"><label>
                选择图文模版
            </label></div>
        <div class="form-inline">
            <div class="form-group">
                <?php
                if (!empty($aMediaList['item'])) {
                    foreach ($aMediaList['item'] as $key => $value) {
                        ?>
                        <div class="radio">
                            <label>
                                <input type="radio" name="media_id" id="media_id" value="<?php echo $value['media_id'];?>">
                            </label>
                        </div>
                        <div class="media-div">
                            <?php
                            foreach($value['content']['news_item'] as $k =>$val) {
                                ?>
                                <div class="appmsg_item">
                                    <h4><a target="_blank" href="<?php echo $val['url'];?>"><?php echo $val['title'];?></a></h4>
                                </div>
                                <?php
                            }
                            ?>
                        </div>
                    <?php

                    }
                }
                ?>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="margin_aa"><label>
                选择群发日期
            </label></div>
        <div class="well">
            <div id="datetimepicker1" class="input-append date">
                <input data-format="yyyy-MM-dd" type="text" name="batchDate">
    <span class="add-on">
      <i data-time-icon="icon-time" data-date-icon="icon-calendar">
      </i>
    </span>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="margin_aa"><label>
                选择群发时间
            </label></div>
        <div class="form-inline">
            <div class="form-group">
                    <?php
                    if (!empty($batchTime)) {
                        foreach ($batchTime as $key => $value) {
                            ?>
                                <label>
                                    <input type="radio" name="batchTime" id="batchTime" value="<?php echo $key;?>"> <?php echo $value;?>
                                </label>
                        <?php
                        }
                    }
                    ?>
            </div>
        </div>
    </div>
        <button type="submit" class="btn btn-primary btn-lg">提交</button>
</div>
</form>

<!-- Footer
================================================== -->
<footer class="bs-docs-footer" role="contentinfo">
    <div class="container">
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="../../static/jquery/jquery-2.1.1.js"></script>
<script src="../../static/bootstrap3.3.2/js/bootstrap.js"></script>
<script src="../../static/plug-in/ladytime/js/bootstrap-datetimepicker.min.js"></script>
<script src="http://res.wx.qq.com/open/js/jweixin-1.0.0.js"></script>
<script type="text/javascript">
    $(function() {
        $('#datetimepicker1').datetimepicker({
            language: 'pt-BR'
        });
    });
</script>
<!--
<script type="text/javascript" language="JavaScript">
    wx.config({
        debug: true, // 开启调试模式,调用的所有api的返回值会在客户端alert出来，若要查看传入的参数，可以在pc端打开，参数信息会通过log打出，仅在pc端时才会打印。
        appId: '', // 必填，公众号的唯一标识
        timestamp: 111, // 必填，生成签名的时间戳
        nonceStr: '', // 必填，生成签名的随机串
        signature: '',// 必填，签名，见附录1
        jsApiList: ["chooseImage"] // 必填，需要使用的JS接口列表，所有JS接口列表见附录2
    });
    wx.ready(function(){
        alert(1111);
        return false;
        // config信息验证后会执行ready方法，所有接口调用都必须在config接口获得结果之后，config是一个客户端的异步操作，所以如果需要在页面加载时就调用相关接口，则须把相关接口放在ready函数中调用来确保正确执行。对于用户触发时才调用的接口，则可以直接调用，不需要放在ready函数中。
    });
    wx.error(function(res){

        // config信息验证失败会执行error函数，如签名过期导致验证失败，具体错误信息可以打开config的debug模式查看，也可以在返回的res参数中查看，对于SPA可以在这里更新签名。

    });
    wx.chooseImage({
        success: function (res) {
            var localIds = res.localIds; // 返回选定照片的本地ID列表，localId可以作为img标签的src属性显示图片
        }
    });
</script>
    -->


</body>
</html>
