<!-- Footer
================================================== -->
<footer class="bs-docs-footer" role="contentinfo">
    <div class="container">
    </div>
</footer>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="<?php echo $GLOBALS['STATICPATH']; ?>bootstrap3.3.2/js/bootstrap.js"></script>
<script type="text/javascript">
</script>
</body>
</html>