<style xmlns="http://www.w3.org/1999/html">
    .clear {
        clear: both;
    }
</style>
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="<?php echo $GLOBALS['description'] ?>">
    <meta name="keywords" content="<?php echo $GLOBALS['keywords'] ?>">
    <meta name="author" content="<?php echo $GLOBALS['author'] ?>">

    <title>
        <?php echo $GLOBALS['title'] ?>
    </title>

    <!-- Bootstrap core CSS -->
    <link href="<?php echo $GLOBALS['STATICPATH']; ?>bootstrap3.3.2/css/bootstrap.css" rel="stylesheet">
    <link href="<?php echo $GLOBALS['STATICPATH']; ?>plug-in/ladytime/css/bootstrap-datetimepicker.min.css" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <link rel="icon" href="/favicon.ico">
</head>
<body>

